---
title: "exp"
output: html_document
date: "2026-05-03"
---

```{r}
library(dplyr)
library(tidyr)
library(ggplot2)
library(readr)
library(magrittr)
```
Create a stimuli counterbalancing list for test

Columns: VOT  (−5, 5, 15, 25, 30, 35, 40, 45, 50, 55, 65, 70 ms), wordpair (dill, dip, din), 

```{r create test sheet}

test.vot <- c(-5, 5, 15, 25, 30, 35, 40, 45, 50, 55, 65, 70)
word.list <- c("dill", "dip", "din")

s.test <- crossing(
  VOT  = test.vot,
  word = word.list,
  rep      = 1:2
) %>%
  mutate(
    # grouping realized through match (), every 4 consecutive VOTs share a quartet number, very clever algebra
    quartet = ((match(VOT, test.vot) - 1) %/% 4) + 1, 
    # convert word to integer
    wp.idx  = match(word, word.list),   
    # Latin-square assignmen
    block   = ((quartet + wp.idx - 2) %% 3) + 1 + 3 * (rep - 1)
  ) %>%
  select(VOT, word, block) 

# sanity check
s.test %>%
  group_by(block) %>%
  summarise(
    n.trials   = n(),
    n.VOTs     = n_distinct(VOT),
    n.dill      = sum(word == "dill")
  )


```
```{r create exposure sheet}

exposure.vot <- seq(-20, 125, 5)

# condition 1
m.d.c1 = 5
sd.d.c1 = 8.94
m.t.c1 = 50
sd.t.c1 = 16.4

get.48tokens.from.vot <- function(m.d, sd.d, m.t, sd.t, seed) {
  set.seed(seed)
  weights.d <- dnorm(exposure.vot, mean = m.d, sd = sd.d)
  weights.t <- dnorm(exposure.vot, mean = m.t, sd = sd.t)
  sample.d <- sample(exposure.vot, size = 24, replace = TRUE, prob = weights.d)
  sample.t <- sample(exposure.vot, size = 24, replace = TRUE, prob = weights.t)
  tibble(VOT    = c(sample.d, sample.t),
    center = rep(c("d", "t"), each = 24))
}

get.3exposures.for.each.cond <- function(m.d, sd.d, m.t, sd.t,
                                         seed1 = 1, seed2 = 2, seed3 = 3) {
  t1 <- get.48tokens.from.vot(m.d, sd.d, m.t, sd.t, seed1) %>% mutate(block = 1)
  t2 <- get.48tokens.from.vot(m.d, sd.d, m.t, sd.t, seed2) %>% mutate(block = 2)
  t3 <- get.48tokens.from.vot(m.d, sd.d, m.t, sd.t, seed3) %>% mutate(block = 3)
  bind_rows(t1, t2, t3)
}

catch.trials <- tibble(
  block = rep(1:3, each = 6),
  VOT = NA_real_,
  center = rep(c("left", "left", "left", "right", "right", "right"), times = 3),
  condition = "c1",
  label = rep(c(0, 1, 0, 1, 0, 1), times = 3)
) %>%
  mutate(word = center)

# tokens.c1 <- get.3exposures.for.each.cond(m.d.c1, sd.d.c1, m.t.c1, sd.t.c1) %>% mutate(condition = "c1") %>%
#   # counterbalance label and word pair
#   group_by(block, center) %>%
#   mutate(label = sample(rep(c(0, 1), each = 12))) %>%
#   group_by(block, center, label) %>%
#   mutate(word = sample(rep(c("dill", "dip", "din"), each = 4))) %>%
#   ungroup()

assign.label.word.to.cond <- function(m.d, sd.d, m.t, sd.t, cond.label,
                                       seed1 = 1, seed2 = 2, seed3 = 3) {
  get.3exposures.for.each.cond(m.d, sd.d, m.t, sd.t, seed1, seed2, seed3) %>%
    mutate(condition = cond.label) %>%
    group_by(block, center) %>%
    mutate(label = sample(rep(c(0, 1), each = 12))) %>%
    group_by(block, center, label) %>%
    mutate(word = sample(rep(c("dill", "dip", "din"), each = 4))) %>%
    ungroup()
}

#add catch trials
tokens.c1 <-assign.label.word.to.cond(m.d.c1, sd.d.c1, m.t.c1, sd.t.c1, "c1")
s.c1.exposure <- bind_rows(tokens.c1, catch.trials)
```



```{r combine exposure and test}

s.c1.exposure %<>% mutate(session = "exposure")
s.test %<>% mutate(session = "test")

s.c1 <- bind_rows(s.c1.exposure, s.test)%>%
  arrange(block, session, VOT)%>%
  mutate(stage = paste0(session, block), randomized_trial = paste0(session, block))

# sanity check the distribution of VOT within s.c1 exposure group 
ggplot(s.c1.exposure, aes(x = VOT)) +
  geom_histogram(binwidth = 5) +
  facet_wrap(~block) +
  labs(title = "VOT distribution", x = "VOT", y = "count")



```
3 exposure block * 4 test order * 2 left or right = 24 combinations

24 combinations * 3 conditions (-20, -10, +20ms) later = 72 combinations 

```{r output}
latin.square <- function(n) {
  outer(1:n, 1:n, function(i, j) ((i + j - 2) %% n) + 1)
}
testLS     <- latin.square(6)[1:4, ]
exposureLS <- latin.square(3)

# need sanity check
sheet_stage_order <- function(test_idx, exposure_idx) {
  t_perm <- testLS[test_idx, ]
  e_perm <- exposureLS[exposure_idx, ]
  stage_seq <- c(
    paste0("test",     t_perm[1]),
    paste0("exposure", e_perm[1]),
    paste0("test",     t_perm[2]),
    paste0("exposure", e_perm[2]),
    paste0("test",     t_perm[3]),
    paste0("exposure", e_perm[3]),
    paste0("test",     t_perm[4]),
    paste0("test",     t_perm[5]),
    paste0("test",     t_perm[6])
  )
  match(s.c1$stage, stage_seq)   # returns 1..9 for each row
}

s.c1 <- s.c1 %>%
  mutate(
    sheet1  = sheet_stage_order(1, 1),
    sheet2  = sheet_stage_order(1, 2),
    sheet3  = sheet_stage_order(1, 3),
    sheet4  = sheet_stage_order(2, 1),
    sheet5  = sheet_stage_order(2, 2),
    sheet6  = sheet_stage_order(2, 3),
    sheet7  = sheet_stage_order(3, 1),
    sheet8  = sheet_stage_order(3, 2),
    sheet9  = sheet_stage_order(3, 3),
    sheet10 = sheet_stage_order(4, 1),
    sheet11 = sheet_stage_order(4, 2),
    sheet12 = sheet_stage_order(4, 3)
  )

cols <- c("VOT", "center", "block", "condition", "label", "word", "stage", "session", "randomized_trial")

#####  left for d, output 12csv
s.c1.leftd <- s.c1 %>%
  mutate(left = "d", right = "t")
for (i in 1:12) {
  sheet_col <- paste0("sheet", i)                    
  filename  <- paste0("/Users/nwang40/Documents/Gitrepo/Spanish-DL/exp1/s_c1_leftd_sheet", i, ".csv")  
  s.c1.leftd %>%
    arrange(.data[[sheet_col]]) %>%
    select(all_of(cols)) %>%
    write_csv(filename)
}

#####  left for t, output 12csv
s.c1.leftt <- s.c1 %>% #change here
  mutate(left = "t", right = "d") #change here
for (i in 1:12) {
  sheet_col <- paste0("sheet", i)                    
  filename  <- paste0("/Users/nwang40/Documents/Gitrepo/Spanish-DL/exp1/s_c1_leftt_sheet", i, ".csv")  #change here
  s.c1.leftt %>%
    arrange(.data[[sheet_col]]) %>%
    select(all_of(cols)) %>%
    write_csv(filename)
}

```







```{r}
# condition 2 and 3
m.d.c2 = m.d.c1 + 10
m.t.c2 = m.t.c1 + 10

m.d.c3 = m.d.c1 + 40
m.t.c3 = m.t.c1 + 40

tokens.c2 <- get.3exposures.for.each.cond(m.d.c2, sd.d.c1, m.t.c2, sd.t.c1) %>% mutate(condition = "c2")
tokens.c3 <- get.3exposures.for.each.cond(m.d.c3, sd.d.c1, m.t.c3, sd.t.c1)%>% mutate(condition = "c3")
```

